# Generated by Django 4.2.16 on 2026-06-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_te', models.CharField(max_length=255, verbose_name='Title (Telugu)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_te', models.TextField(verbose_name='Description (Telugu)')),
                ('significance_en', models.TextField(blank=True, verbose_name='Significance (English)')),
                ('significance_te', models.TextField(blank=True, verbose_name='Significance (Telugu)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Event Time')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Category Name (English)')),
                ('name_te', models.CharField(max_length=255, verbose_name='Category Name (Telugu)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_te', models.CharField(max_length=255, verbose_name='Title (Telugu)')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, verbose_name='Subtitle (English)')),
                ('subtitle_te', models.CharField(blank=True, max_length=500, verbose_name='Subtitle (Telugu)')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Slide Image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_te', models.CharField(max_length=255, verbose_name='Title (Telugu)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_te', models.TextField(verbose_name='Content (Telugu)')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'News & Announcement',
                'verbose_name_plural': 'News & Announcements',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Seva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Seva Name (English)')),
                ('name_te', models.CharField(max_length=255, verbose_name='Seva Name (Telugu)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_te', models.TextField(verbose_name='Description (Telugu)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sevas/', verbose_name='Seva Image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Seva',
                'verbose_name_plural': 'Sevas',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Sloka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_te', models.CharField(max_length=255, verbose_name='Title (Telugu)')),
                ('content_en', models.TextField(verbose_name='Sloka Content (English)')),
                ('content_te', models.TextField(verbose_name='Sloka Content (Telugu)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Sloka',
                'verbose_name_plural': 'Slokas',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TempleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name_en', models.CharField(max_length=255, verbose_name='Temple Name (English)')),
                ('temple_name_te', models.CharField(max_length=255, verbose_name='Temple Name (Telugu)')),
                ('history_en', models.TextField(verbose_name='History (English)')),
                ('history_te', models.TextField(verbose_name='History (Telugu)')),
                ('address_en', models.TextField(verbose_name='Address (English)')),
                ('address_te', models.TextField(verbose_name='Address (Telugu)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('google_maps_link', models.URLField(blank=True, max_length=500, verbose_name='Google Maps Link')),
            ],
            options={
                'verbose_name': 'Temple Information',
                'verbose_name_plural': 'Temple Information',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('caption_en', models.CharField(blank=True, max_length=500, verbose_name='Caption (English)')),
                ('caption_te', models.CharField(blank=True, max_length=500, verbose_name='Caption (Telugu)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='temple_content.gallerycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
