"""
Django settings for vaibhava_temple project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
import dj_database_url
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-dev-key"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

# CORS_URLS_REGEX = r"^/.*$"

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders", 
    "rest_framework",
    "auditlog",
    "import_export",
    "storages",
    "temple_content.apps.TempleContentConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = 'vaibhava_temple.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'vaibhava_temple.wsgi.application'


# during production should change this as its for local db testing
DATABASES = {
    "default": dj_database_url.config(
        default=f"postgresql://{os.environ.get('DB_USER', 'temple_user')}:{os.environ.get('DB_PASSWORD', 'qwerty')}@{os.environ.get('DB_HOST', 'localhost')}:{os.environ.get('DB_PORT', '5432')}/{os.environ.get('DB_NAME', 'vaibhava_temple_db')}",
        conn_max_age=600,
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     },
# }
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

AWS_ACCESS_KEY_ID = config("R2_ACCESS_KEY_ID")

AWS_SECRET_ACCESS_KEY = config("R2_SECRET_ACCESS_KEY")

AWS_STORAGE_BUCKET_NAME = config("R2_BUCKET_NAME")

AWS_S3_ENDPOINT_URL = (
    f"https://{config('R2_ACCOUNT_ID')}.r2.cloudflarestorage.com"
)

AWS_S3_CUSTOM_DOMAIN = (
    config("R2_PUBLIC_URL").replace("https://", "")
)

AWS_S3_REGION_NAME = "auto"

AWS_S3_SIGNATURE_VERSION = "s3v4"

AWS_LOCATION = ""

AWS_S3_VERIFY = True

AWS_QUERYSTRING_AUTH = False

AWS_DEFAULT_ACL = None

AWS_S3_FILE_OVERWRITE = False

AWS_S3_ADDRESSING_STYLE = "virtual"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = config("R2_PUBLIC_URL") + "/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Admin session expires after 1 hour of inactivity
SESSION_COOKIE_AGE = 60 * 60   # 3600 seconds = 1 hour

# Reset expiry timer on every request
SESSION_SAVE_EVERY_REQUEST = True

# Close session when browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",    
    ],
}

JAZZMIN_SETTINGS = {
    "site_header": "Sri Vaibhava Venkateswara Swamy Devasthanam Portal",
    "site_title": "Sri Vaibhava Venkateswara Swamy Devasthanam Administration",
    "site_brand": "Sri ",
    "index_title": "Temple Content Management",
    "welcome_sign": "Welcome to the Sri Vaibhava Venkateswara Swamy Devasthanam Portal",
    "copyright": "Sri Vaibhav Venkateswara Swamy Devasthanam",
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    
    "search_model": ["auth.user"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "Public API", "url": "/api/home/", "new_window": True},
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "temple_content.TempleInformation": "fas fa-gopuram",
        "temple_content.HeroSlide": "fas fa-images",
        "temple_content.Sloka": "fas fa-book-open",
        "temple_content.Event": "fas fa-calendar-alt",
        "temple_content.NewsAnnouncement": "fas fa-newspaper",
        "temple_content.GalleryCategory": "fas fa-folder-open",
        "temple_content.GalleryImage": "fas fa-photo-video",
        "temple_content.Seva": "fas fa-hands",
        "temple_content.ContactSubmission": "fas fa-envelope",
        "auditlog.LogEntry": "fas fa-history",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    
    "site_logo": "admin/img/logo.png",
    "login_logo": "admin/img/logo.png",
    "site_icon": "admin/img/logo.png",
    "custom_css": "admin/css/custom_admin.css",
}

JAZZMIN_UI_TWEAKS = {
      "navbar": "navbar-white navbar-light",
    "brand_colour": "navbar-maroon",
    "accent": "accent-warning",
    "sidebar": "sidebar-dark-danger",
    "navbar_fixed": True,
    "sidebar_fixed": True,
}
# JAZZMIN_SETTINGS = {
#     "site_header": "Sri Vaibhava Venkateswara Swamy Devasthanam Portal",
#     "site_title": "Sri Vaibhava Venkateswara Swamy Devasthanam Administration",
#     "site_brand": "Sri Vaibhava Venkateswara Swamy",
#     "index_title": "Temple Content Management",
#     "welcome_sign": "Welcome to the Sri Vaibhava Venkateswara Swamy Devasthanam Portal",
#     "copyright": "Sri Vaibhav Venkateswara Swamy Devasthanam",

#     # # ── Logo (was None before, and wrongly placed in UI_TWEAKS) ──
#     # "site_logo":        "admin/img/logo.png",
#     # "login_logo":       "admin/img/logo.png",
#     # "login_logo_dark":  "admin/img/logo.png",
#     # "site_logo_classes": "img-fluid",
#     # "site_icon":        "admin/img/logo.png",

#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "search_model": ["auth.user"],
#     "topmenu_links": [
#         {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"name": "Public API", "url": "/api/home/", "new_window": True},
#     ],
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "temple_content.TempleInformation": "fas fa-gopuram",
#         "temple_content.HeroSlide": "fas fa-images",
#         "temple_content.Sloka": "fas fa-book-open",
#         "temple_content.Event": "fas fa-calendar-alt",
#         "temple_content.NewsAnnouncement": "fas fa-newspaper",
#         "temple_content.GalleryCategory": "fas fa-folder-open",
#         "temple_content.GalleryImage": "fas fa-photo-video",
#         "temple_content.Seva": "fas fa-hands",
#         "temple_content.ContactSubmission": "fas fa-envelope",
#         "auditlog.LogEntry": "fas fa-history",
#     },
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
#     "related_modal_active": True,
#     "use_google_fonts_cdn": True,
#     "show_ui_builder": True,
#     "changeform_format": "horizontal_tabs",
# }


# JAZZMIN_UI_TWEAKS = {
#     "brand_colour": "navbar-danger",
#     "accent": "accent-danger",
#     "navbar": "navbar-dark",
#     "navbar_fixed": True,
#     "sidebar_fixed": True,
#     "sidebar": "sidebar-dark-danger",
#     "sidebar_nav_compact_style": True,
#     "sidebar_nav_child_indent": True,
    
#     # "site_logo": "admin/img/temple_logo.svg",          # add this
#     # "site_logo_classes": "img-circle elevation-3",      # add this
#     # "site_icon": "admin/img/temple_logo.svg",           # add this (browser tab icon)
#     # "custom_css": "admin/css/custom_admin.css",         # add this
#     # "custom_js": "admin/js/custom_admin.js",
#     # "site_logo": "admin/img/logo.png",
#     # "site_logo_classes": "img-fluid",
#     # "login_logo": "admin/img/logo.png",
#     # "login_logo_dark": "admin/img/logo.png", 
# }

# from pathlib import Path


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ht#k2az0&z!73_@z*^i_n$(umd*1#4ld+2cc^irwg)8i^7-k*@'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'vaibhava_temple.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'vaibhava_temple.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
